name: Build Neovim AppImage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.05

      - name: Build Neovim AppImage
        run: |
          nix bundle --bundler github:ralismark/nix-appimage .#neovim
          ls
          cp nvim.Appimage nix-nvim.Appimage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: neovim-appimage
          path: nix-nvim.AppImage

