name: Build Neovim AppImage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-25.05

      - name: Build Neovim AppImage
        run: |
          nix bundle --bundler github:ralismark/nix-appimage .#neovim
          cp nvim.AppImage nix-nvim.AppImage

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create draft release if it doesn't exist
        run: |
          gh release view manual-release || \
          gh release create manual-release --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload AppImage to release
        run: |
          gh release upload manual-release nix-nvim.AppImage --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

